Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.11.6/x64/lib/python3.11/site-packages/jupyter_cache/executors/utils.py", line 58, in single_nb_execution
    executenb(
  File "/opt/hostedtoolcache/Python/3.11.6/x64/lib/python3.11/site-packages/nbclient/client.py", line 1305, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.11.6/x64/lib/python3.11/site-packages/jupyter_core/utils/__init__.py", line 173, in wrapped
    return loop.run_until_complete(inner)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.11.6/x64/lib/python3.11/asyncio/base_events.py", line 653, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.11.6/x64/lib/python3.11/site-packages/nbclient/client.py", line 705, in async_execute
    await self.async_execute_cell(
  File "/opt/hostedtoolcache/Python/3.11.6/x64/lib/python3.11/site-packages/nbclient/client.py", line 1058, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/opt/hostedtoolcache/Python/3.11.6/x64/lib/python3.11/site-packages/nbclient/client.py", line 914, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
# plot the data
fig, ax = plt.subplots()
ax.plot(data_stream.datetime64,
        data_stream.data[0, :],  # data_stream.data is a 2d array, so we need
                                 # to specify which column we want to plot
        label=data_stream.header[0],
        linestyle="none",
        marker=".",)
plt.xticks(rotation=45)
ax.set_xlabel("Time (UTC)")
ax.set_ylabel(data_stream.header[0])
plt.show()
fig.tight_layout()
------------------


[0;31m---------------------------------------------------------------------------[0m
[0;31mValueError[0m                                Traceback (most recent call last)
Cell [0;32mIn[4], line 3[0m
[1;32m      1[0m [38;5;66;03m# plot the data[39;00m
[1;32m      2[0m fig, ax [38;5;241m=[39m plt[38;5;241m.[39msubplots()
[0;32m----> 3[0m [43max[49m[38;5;241;43m.[39;49m[43mplot[49m[43m([49m[43mdata_stream[49m[38;5;241;43m.[39;49m[43mdatetime64[49m[43m,[49m
[1;32m      4[0m [43m        [49m[43mdata_stream[49m[38;5;241;43m.[39;49m[43mdata[49m[43m[[49m[38;5;241;43m0[39;49m[43m,[49m[43m [49m[43m:[49m[43m][49m[43m,[49m[43m  [49m[38;5;66;43;03m# data_stream.data is a 2d array, so we need[39;49;00m
[1;32m      5[0m [43m                                 [49m[38;5;66;43;03m# to specify which column we want to plot[39;49;00m
[1;32m      6[0m [43m        [49m[43mlabel[49m[38;5;241;43m=[39;49m[43mdata_stream[49m[38;5;241;43m.[39;49m[43mheader[49m[43m[[49m[38;5;241;43m0[39;49m[43m][49m[43m,[49m
[1;32m      7[0m [43m        [49m[43mlinestyle[49m[38;5;241;43m=[39;49m[38;5;124;43m"[39;49m[38;5;124;43mnone[39;49m[38;5;124;43m"[39;49m[43m,[49m
[1;32m      8[0m [43m        [49m[43mmarker[49m[38;5;241;43m=[39;49m[38;5;124;43m"[39;49m[38;5;124;43m.[39;49m[38;5;124;43m"[39;49m[43m,[49m[43m)[49m
[1;32m      9[0m plt[38;5;241m.[39mxticks(rotation[38;5;241m=[39m[38;5;241m45[39m)
[1;32m     10[0m ax[38;5;241m.[39mset_xlabel([38;5;124m"[39m[38;5;124mTime (UTC)[39m[38;5;124m"[39m)

File [0;32m/opt/hostedtoolcache/Python/3.11.6/x64/lib/python3.11/site-packages/matplotlib/axes/_axes.py:1721[0m, in [0;36mAxes.plot[0;34m(self, scalex, scaley, data, *args, **kwargs)[0m
[1;32m   1478[0m [38;5;250m[39m[38;5;124;03m"""[39;00m
[1;32m   1479[0m [38;5;124;03mPlot y versus x as lines and/or markers.[39;00m
[1;32m   1480[0m 
[0;32m   (...)[0m
[1;32m   1718[0m [38;5;124;03m(``'green'``) or hex strings (``'#008000'``).[39;00m
[1;32m   1719[0m [38;5;124;03m"""[39;00m
[1;32m   1720[0m kwargs [38;5;241m=[39m cbook[38;5;241m.[39mnormalize_kwargs(kwargs, mlines[38;5;241m.[39mLine2D)
[0;32m-> 1721[0m lines [38;5;241m=[39m [[38;5;241m*[39m[38;5;28mself[39m[38;5;241m.[39m_get_lines([38;5;28mself[39m, [38;5;241m*[39margs, data[38;5;241m=[39mdata, [38;5;241m*[39m[38;5;241m*[39mkwargs)]
[1;32m   1722[0m [38;5;28;01mfor[39;00m line [38;5;129;01min[39;00m lines:
[1;32m   1723[0m     [38;5;28mself[39m[38;5;241m.[39madd_line(line)

File [0;32m/opt/hostedtoolcache/Python/3.11.6/x64/lib/python3.11/site-packages/matplotlib/axes/_base.py:303[0m, in [0;36m_process_plot_var_args.__call__[0;34m(self, axes, data, *args, **kwargs)[0m
[1;32m    301[0m     this [38;5;241m+[39m[38;5;241m=[39m args[[38;5;241m0[39m],
[1;32m    302[0m     args [38;5;241m=[39m args[[38;5;241m1[39m:]
[0;32m--> 303[0m [38;5;28;01myield from[39;00m [38;5;28;43mself[39;49m[38;5;241;43m.[39;49m[43m_plot_args[49m[43m([49m
[1;32m    304[0m [43m    [49m[43maxes[49m[43m,[49m[43m [49m[43mthis[49m[43m,[49m[43m [49m[43mkwargs[49m[43m,[49m[43m [49m[43mambiguous_fmt_datakey[49m[38;5;241;43m=[39;49m[43mambiguous_fmt_datakey[49m[43m)[49m

File [0;32m/opt/hostedtoolcache/Python/3.11.6/x64/lib/python3.11/site-packages/matplotlib/axes/_base.py:499[0m, in [0;36m_process_plot_var_args._plot_args[0;34m(self, axes, tup, kwargs, return_kwargs, ambiguous_fmt_datakey)[0m
[1;32m    496[0m     axes[38;5;241m.[39myaxis[38;5;241m.[39mupdate_units(y)
[1;32m    498[0m [38;5;28;01mif[39;00m x[38;5;241m.[39mshape[[38;5;241m0[39m] [38;5;241m!=[39m y[38;5;241m.[39mshape[[38;5;241m0[39m]:
[0;32m--> 499[0m     [38;5;28;01mraise[39;00m [38;5;167;01mValueError[39;00m([38;5;124mf[39m[38;5;124m"[39m[38;5;124mx and y must have same first dimension, but [39m[38;5;124m"[39m
[1;32m    500[0m                      [38;5;124mf[39m[38;5;124m"[39m[38;5;124mhave shapes [39m[38;5;132;01m{[39;00mx[38;5;241m.[39mshape[38;5;132;01m}[39;00m[38;5;124m and [39m[38;5;132;01m{[39;00my[38;5;241m.[39mshape[38;5;132;01m}[39;00m[38;5;124m"[39m)
[1;32m    501[0m [38;5;28;01mif[39;00m x[38;5;241m.[39mndim [38;5;241m>[39m [38;5;241m2[39m [38;5;129;01mor[39;00m y[38;5;241m.[39mndim [38;5;241m>[39m [38;5;241m2[39m:
[1;32m    502[0m     [38;5;28;01mraise[39;00m [38;5;167;01mValueError[39;00m([38;5;124mf[39m[38;5;124m"[39m[38;5;124mx and y can be no greater than 2D, but have [39m[38;5;124m"[39m
[1;32m    503[0m                      [38;5;124mf[39m[38;5;124m"[39m[38;5;124mshapes [39m[38;5;132;01m{[39;00mx[38;5;241m.[39mshape[38;5;132;01m}[39;00m[38;5;124m and [39m[38;5;132;01m{[39;00my[38;5;241m.[39mshape[38;5;132;01m}[39;00m[38;5;124m"[39m)

[0;31mValueError[0m: x and y must have same first dimension, but have shapes (68551,) and (2,)

